include/topotoolbox.h, src/topotoolbox.c, test/CMakeLists.txt, test/versioninfo.cpp
Windows requires extra attributes to export the symbols from a shared library. Macros similar to the ones defined here are a typical way of handling such attributes.
include/topotoolbox.h adds the TOPOTOOLBOX_API macro, which controls which __declspec attribute is attached to exported API functions. The TOPOTOOLBOX_BUILD flag controls whether the shared library is being built, in which case the symbols must be exported, or used, in which case they must be imported. An API function `has_topotoolbox` is added. This function returns 1 (true), and can be used to test that everything is linked correctly. As more functions are added to the library, this functionality may become less useful.
src/topotoolbox.c defines the TOPOTOOLBOX_BUILD macro and the `has_topotoolbox` function. …
=> Add export definition macros

.github/workflows/ci.yaml
This creates a workflow that checks out the repository, then builds and tests the repository with our CMake build system. The action is run on Ubuntu with gcc and clang, macos with clang and Windows with MSVC.
.github/workflows/ci.yaml contains the configuration for the CI workflow. It is based loosely on the cmake-multi-platform starter workflow provided by GitHub.
=> Add continuous integration with GitHub actions

.clang-format, .github/workflows/ci.yaml
This commit begins to solidify a style guide for
libtopotoolbox (#13). clang-format addresses code formatting and not other aspects of style, however, which will need to be managed using other tools.
.clang-format is the clang-format configuration file output by clang-format -style=Google --dump-config corresponding to the Google C++ style guide
.github/workflows/ci.yaml is changed to use the
jidicula/clang-format-action to run clang-format on the source files in the repository.
=> Add a .clang-format file and run format checks during CI

include/topotoolbox.h, src/CMakeLists.txt, src/fillsinks.c, src/morphology/reconstruct.c, src/morphology/reconstruct.h, test/CMakeLists.txt, test/fillsinks.cpp
Resolves #7
TopoToolbox fills sinks in digital elevation models using grayscale morphological reconstruction. This algorithm repeatedly dilates a "marker" image while constraining it to lie below a "mask" image. The negative DEM is used as the mask while the marker is identical to the negative DEM on the boundary pixels but negative infinity in its interior. The morphological reconstruction iteratively fills in the interior of the marker image, but does not descend into sinks of the mask.
src/morphology/reconstruct.c implements the sequential reconstruction algorithm presented by Vincent (1993). The algorithm repeatedly scans in alternating directions through the DEM, updates the marker image based on the values of the marker and mask in a neighborhood around the given pixel and …
=> Implement sink filling using morphological reconstruction

CMakeLists.txt
src/CMakeLists.txt now uses include(CTest) to enable the CTest module and then only adds the build instructions in the test/ directory if BUILD_TESTING is enabled. It is enabled by default. CMake can be configured to build just the library with no tests by running
```
> cmake -B build -DBUILD_TESTING=OFF
```
=> Control whether tests are built with the BUILD_TESTING flag

CMakeLists.txt, test/fillsinks.cpp
This sets the C++ standard to C++11 and the C standard to C99.
Compiler warnings "/W4" and "-Wall -Wextra -Wpedantic" are used for MSVC and GCC/Clang, respectively. The unused parameter warning is turned off for all compilers now because it warns about argc, argv not being used in main functions.
Compiler warnings are treated as errors using CMake's CMAKE_COMPILE_WARNING_AS_ERROR variable. This can be turned off on the command line with cmake --compile-no-warning-as-error if necessary. For now, it is useful to ensure CI fails when compiler warnings are emitted.
test/fillsinks.cpp is modified to ensure that it builds with the new compiler settings. This requires removing a hexadecimal floating point literal, which is added in C++17 and modifying some of the types of variables passed to the …
=> Set C/C++ standards and add more aggressive compiler warnings

src/morphology/reconstruct.c
This now uses a for loop with an iteration counter up to a maximum number of iterations, which is declared as a named constant. The loop is ended early if the scans stop changing, which indicates convergence. This ensures that the reconstruction will not run forever even in the presence of NaNs or some other reason why it wouldn't converged.
Note that we do not current signal to the caller that the reconstruction has not converged. A value could be returned from this function to indicate whether it has converged, but it is unclear to me what the caller (namely `fillsinks`) should do with that information.
=> Restructure the morphological reconstruction loop

src/fillsinks.c
By using && in this conditional, this only initialized the output/marker with pixels in the corners when we needed to initialize all the boundary pixels. Switching the && to || ensures that all of the boundary pixels are set equal to their value in the inverted DEM before the reconstruction algorithm is run.
=> Initialize all pixels on the boundary in fillsinks

CMakeLists.txt, README.md, cmake/TopoToolboxConfig.cmake.in, include/topotoolbox.h, src/CMakeLists.txt
This sets up a CMake Config package for libtopotoolbox that will allow it to be installed and more easily built by other CMake projects. The end goal is to use the libtopotoolbox CMake package with scikit-build-core to install things properly for pytopotoolbox.
CMakeLists.txt adds a target to install the topotoolbox library and header file in the appropriate lib/ and include/ directories, which are set by GNUInstallDirs. It sets include/topotoolbox.h to be a PUBLIC_HEADER, which allows it to be installed by the install command.
IMPORTANT: A static library is now built by default. The shared library can be built by passing the option -DBUILD_SHARED_LIBS=ON to cmake.
CMakeLists.txt also provides a package configuration that enables CMake's `find_package` to find the library. Something like …
=> Add CMake package configuration

.github/workflows/ci.yaml, CMakeLists.txt, README.md, src/CMakeLists.txt
This series of commits updates the CMake project configuration to allow dependencies to install libtopotoolbox successfully with a minimum of extra noise.
src/CMakeLists.txt is updated to point to ${topotoolbox_SOURCE_DIR}/include for the header files, which should allow projects building libtopotoolbox as a dependency to find the headers properly.
CMakeLists.txt now uses a project-specific TT_BUILD_TESTS flag to control whether the internal tests are built. This is off by default, so dependencies will not build the tests alongside the library. The build instructions in the README have been updated, and CI now uses this flag.
=> Fixes to allow dependencies to install libtopotoolbox cleanly

include/topotoolbox.h, src/CMakeLists.txt, src/identifyflats.c, test/CMakeLists.txt, test/random_dem.cpp
Resolves #8 
src/identifyflats.c adds the function `identifyflats`, which labels pixels in a DEM whose elevation is equal to the minimum elevation of their neighbors (flats) or whose elevation is equal to that of a neighboring flat (sills).
src/CMakeLists.txt adds src/identifyflats.c the library sources
include/topotoolbox.h adds the prototype for identifyflats
test/fillsinks.cpp is renamed to test/random_dem.cpp because we use random DEMs to test a variety of TopoToolbox functions
test/random_dem.cpp now runs `identifyflats` after `fillsinks` to label flats and sills in the DEM. The following properties are tested:
1. No flat pixel should have a neighbor that is lower than it
2. Every sill pixel should have at least one neighbor lower than it
3. Every sill pixel should border a flat …
=> Identify flat pixels in DEM

src/topotoolbox.c, test/random_dem.cpp
has_topotoolbox doesn't require any input parameters. The prototype in include/topotoolbox.h does use has_topotoolbox(void) to indicate this, but the implementation in src/topotoolbox.c does not. This caused CI errors on macos + clang.
src/topotoolbox.c adds a void parameter to the signature of has_topotoolbox
=> Complete the function prototype for has_topotoolbox

include/topotoolbox.h, src/identifyflats.c, test/random_dem.cpp
Knowing how many flat pixels there are is useful for computing the costs for the gray-weighted distance transform. It is easy enough to compute this in `identifyflats` as flat pixels are identified, and return the number of flats from the function.
include/topotoolbox.h now indicates that `identifyflats` returns a ptrdiff_t.
src/identifyflats.c now increments a counter every time a flat is identified and returns that counter
test/random_dem.cpp is modified to check that the number of identified flats returned from `identifyflats` is equal to those identified while running the test.
=> Return the number of flats from identifyflats

include/topotoolbox.h, src/CMakeLists.txt, src/gwdt.c, test/random_dem.cpp
This PR resolves #9, computing the costs for the gray-weighted distance transform.
The main challenge here is in identifying the connected components of flat pixels, which in MATLAB is done with `bwconncomp`. I've implemented a connected components labeling algorithm, which closely follows the OCL algorithm discussed in [this paper](https://doi.org/10.1016/j.patcog.2017.04.018). 
The one modification that I've made is to store the union-find data structure that maintains provisional component labels in the output arrays. This avoids dynamically allocating memory for the union-find data structure, but I am worried that it might be confusing and hard to maintain going forward. 
@Teschl if you have some time, would you mind looking over this PR to see if you can understand what it is doing? …
=> Compute costs for the gray-weighted distance transform

README.md, docs/CONTRIBUTING.md
Closes #29
Closes #13 
This adds a draft of contributing guidelines and moves the build instructions from the README to CONTRIBUTING.md. 
The CONTRIBUTING.md includes a section for formatting and style, which provides a place to accumulate information on code style. We can always move that to a separate STYLE.md or similar if that section gets too large.
The README includes some links to other TopoToolbox projects and sites, some of which are not available yet. In particular the link for the libtopotoolbox documentation is broken, but it will be fixed shortly when #28 is resolved.
=> Contributing Guidelines

.github/workflows/docs.yaml
This was previously used for testing in a separate branch that only existed in my fork, it is no longer necessary for the main repository.
=> Remove sphinx-doxygen branch from docs workflow

docs/CONTRIBUTING.md
GitHub's Markdown renderer displays a raw URL as an HTML link, but myst-parser does not, so this link did not show up in our online documentation. The angle brackets should make it display properly in both circumstances.
=> Add explicit link to topotoolbox.github.io

.github/workflows/docs.yaml
=> Use pip to install Python dependencies in docs workflow

.github/workflows/docs.yaml, docs/requirements.txt
Closes #42 
docs/requirements.txt fixes versions for the dependencies required to build the docs with Sphinx. This is then used in the docs workflow to install those dependencies before building.
=> Add docs/requirements.txt to install docs' Python build deps

.github/workflows/ci.yaml, src/excesstopography.c
We must remember to do this for every file that implements TOPOTOOLBOX_API functions, because it controls whether the Windows __declspec is dllexport or dllimport. This only affects Windows, so it did not show up on our Unix development machines, and we didn't catch this in our CI because we only ever build static libraries.
.github/workflows/ci.yaml adds a shared library build step to catch errors like this.
=> Define TOPOTOOLBOX_BUILD in excesstopography.c

src/excesstopography.c, test/excesstopography.cpp
Fixes #53
This bug turns out to result from numerical issues when applying the eikonal solver, especially when the elevations are large and the slopes are small. You end up taking the square root of a negative number and the resulting proposal is NaN, which is never accepted and so the infinite elevations are left in the DEM. Modifying the eikonal solution formula seems to avoid these numerical problems even while still using single precision data.
A new test is added to test/excesstopography.cpp to verify this behavior. It does not directly test the eikonal solver, but instead tests the case from #53.
=> excesstopography: Fix numerical error in eikonal solver

.github/workflows/release.yaml
This PR implements a GitHub Actions workflow that automatically tags and releases a source code archive every Monday.
We are starting to get to the point where we need better control over which version of libtopotoolbox we are using in downstream projects. There are some outstanding issues (namely #23) that I have held off on because they will break pytopotoolbox, and we don't have a good way of cleanly managing that transition.
These releases are not meant to be "official" libtopotoolbox releases. They exist only to allow downstream projects to pin the version of libtopotoolbox they are currently using. The version numbering explicitly does not follow semantic versioning, and each weekly release should be considered potentially breaking. A disclaimer to that effect is included in the …
=> Implement automatic weekly releases

test/CMakeLists.txt, test/excesstopography.cpp, test/gwdt.cpp, test/random_dem.cpp, test/utils.c, test/utils.h
Closes #56 
This commit introduces an internal module test/utils.c where we can put test-specific utilities to prevent duplication. The pcg4d random number generator that we use in the three test executables has been moved into this module.
This may not be the final location for these things. I'm not a huge fan of a catch-all `utils` file, but it works for now.
=> Move pcg4d to test/utils.c

CMakeLists.txt
I added the -g to generate debug information because I had thought that it was not getting generated properly when
CMAKE_BUILD_TYPE=Debug. This was actually because the default CMAKE_BUILD_TYPE is not Debug but a toolchain-specific value. If I explicitly build with CMAKE_BUILD_TYPE=Debug, -g is set and we get debug information.
=> Remove the -g flag from compile options

.github/workflows/ci.yaml
Fixes #61
A new job is added to .github/workflows/ci.yaml that builds the Debug configuration and runs the tests with AddressSanitizer on Ubuntu. The other jobs build the Release configuration and run the tests on various operating systems. The Release jobs also continue to build the shared library to confirm that it links properly.
=> Run only one Debug job

include/topotoolbox.h, src/excesstopography.c, src/fillsinks.c, src/gwdt.c, src/identifyflats.c, src/morphology/reconstruct.c, src/morphology/reconstruct.h, test/excesstopography.cpp, test/random_dem.cpp
This PR renames the `nrows` and `ncols` arguments of every libtopotoolbox function to a single `dims[2]` argument. As discussed elsewhere (#23 #68), this is an ergonomic change rather than a functional one. It only prevents the awkward situation of having to pass the number of columns to an argument named `nrows` when using a row-major array.
This is a breaking change. Packages that use libtopotoolbox now must create and pass a two-element array containing the dimensions. Column-major arrays should use `ptrdiff_t dims[2] = {nrows, ncols};`, while row-major arrays should use `ptrdiff_t dims[2] = {ncols,nrows};`
Partially addresses #23
=> Pass `dims` to functions

.github/workflows/ci.yaml
Resolves #71
This PR should reduce the amount of time CI spends configuring the CMake build system on Windows by 
1. Switching to the Ninja generator rather than using Visual Studio
2. Removing extra configuration types.
It is still a bit slower than the Linux and macos builds, but not 4 times as slow.
=> Improve CMake configuration time on Windows in CI

src/morphology/reconstruct.c
Correctly fixes #76.
I unfortunately merged #77, which was not fully correct. The algorithm seems to converge despite such errors, which is why the tests all seem to pass.
=> Scan all the way to 0

include/topotoolbox.h, src/fillsinks.c, src/morphology/reconstruct.c, src/morphology/reconstruct.h, test/random_dem.cpp
Resolves #74
include/topotoolbox.h now has a new `fillsinks_hybrid` API declaration as well as documentation for this function.
src/fillsinks.c defines `fillsinks_hybrid`, which is identical to `fillsinks`, except that it calls `reconstruct_hybrid`.
src/morphology/reconstruct.h adds the `reconstruct_hybrid` declaration.
src/morphology/reconstruct.c implements `reconstruct_hybrid` by adding
1. A FIFO queue implementation called `PixelQueue`
2. A modified `backward_scan` that fills a PixelQueue if provided.
3. The `propagate` step, which updates the image through a breadth-first search.
test/random_dem.cpp now alternates between testing the `fillsinks` and `fillsinks_hybrid` implementations.
=> Implement hybrid morphological reconstruction for fillsinks

docs/conf.py, docs/index.rst
This adds a GitHub icon to the header that links to the repository as well as some text including a link to the repository from the landing page.
=> Add links to the GitHub repository to the docs

docs/api.rst
This label did not get properly renamed during #75.
=> Refer to the correct flow routing function in docs

include/topotoolbox.h, src/flow_routing.c, test/random_dem.cpp
Closes #84
This function converts the source pixels and the flow directions to target pixels for each edge.
include/topotoolbox.h adds flow_routing_targets to the API and documents the function.
src/flow_routing.c implements flow_routing_targets.
test/random_dem.cpp adds a test that compares the offset implied by the flow direction to the offset between source and target.
=> Implement flow_routing_targets

docs/api.rst
I forgot to add the new function to `docs/api.rst` in #85. 
It would be nice if we could generate `docs/api.rst` automatically from functions with the `TOPOTOOLBOX_API` qualifier.
=> Add flow_routing_targets to API documentation

docs/api.rst
Closes #88
The doxygenfile direction outputs an entry for everything Doxygen documents in the given file. Since the public API is defined in include/topotoolbox.h, this will work.
The :sections: func option displays only functions, to prevent displaying the unhelpful TOPOTOOLBOX_VERSION_* defines. This may need to be changed in the future if additional declarations (i.e. structs, other defines) need to be documented.
=> Use doxygenfile directive to automatically generate API listing

include/topotoolbox.h
@bgailleton: I noticed that your documentation wasn't displaying properly on our website. You need the `/**` at the start of the comment for Doxygen to pick it up. I also changed some of the indentation, but this is actually not very consistent across the different doc comments anyway. At the moment clang-format doesn't really format the doc comments. It might be a good idea to find some tooling to maintain these more consistently.
=> Formatting changes to the docs

CMakeLists.txt, docs/CMakeLists.txt, src/CMakeLists.txt, test/CMakeLists.txt
Fixes #81 
This change adds a bunch of comments to the various `CMakeLists.txt` files throughout the project that explains why we run the various CMake commands. This hopefully makes it easier for future contributors and maintainers to understand the build system.
=> Add inline documentation of the build system

include/topotoolbox.h, src/flow_accumulation.c, test/random_dem.cpp
This function computes the same thing as `flow_accumulation`, but it uses a weighted edge list rather than the source pixel and flow direction.
This presents a more convenient interface for certain downstream applications which otherwise need to carry around the flow direction raster. It should also work equally well for multiple and single flow directions because it supports edge weights and edge lists that are of a different size than the DEM.
include/topotoolbox.h has the function declaration.
src/flow_accumulation.c implements `flow_accumulation_edgelist`
test/random_dem.cpp runs `flow_accumulation_edgelist` and checks to make sure it has identical results to `flow_accumulation`.
---
@Teschl: This might be useful once it is merged for the `StreamObject` constructor. You wouldn't have …
=> Compute flow accumulation with a weighted edge list

include/topotoolbox.h
`gradient8` got put in between a Graphflood function and its Doxygen comment.
=> Move declaration of `gradient8` and its Doxygen comment

docs/Doxyfile.in, include/topotoolbox.h
This should help diagnose problems with the Doyxgen documentation on CI. However, there are warnings related to undocumented macros, which are not rendered in the generated Sphinx documentation anyway, so I turn those errors off
include/topotoolbox.h also fixes existing Doyxgen warnings by renaming parameters and moving around some that got out of sync with the function definitions.
=> Error on warnings in Doxygen and switch off undocumented warnings

test/random_dem.cpp
C++ `new` throws an exception rather than returning a null pointer on allocation failure. These checks are not necessary and removing them cleans up the test code somewhat.
=> Remove null pointer checks from test/random_dem.cpp

test/random_dem.cpp
This allows benchmarking runs to use differently sized DEMs. The test that CTest runs, defined in test/CMakeLists.txt, does not pass command line arguments and will use the previous default size.
=> Read DEM size from command line

test/profiler.h, test/random_dem.cpp
This commit adds a very simple block profiler. The profiler times how long it takes to execute a block, sums the total elapsed time for a given block that may be executed more than once by the test, and prints the results. See the comment at the top of test/profiler.h for usage instructions and caveats.
The profiling code should have minimal overhead, so it will not interfere with the normal automated testing procedure. Proper benchmarks using this profiler should be run on dedicated hardware (i.e. not on CI) with CMAKE_BUILD_TYPE=Release.
test/profiler.h implements the block profiler
test/random_dem.cpp profiles the `route_flow`, `route_flow_hybrid`, `gradient8` and `gradient8_mp` member functions of the `FlowRoutingData` class.
=> Implement block profiler

.github/workflows/ci.yaml
The release build will now directly run the random_dem test executable, which includes output from the profiler, and pass the results through `jq`, which is included in the GitHub-provided runners. Any invalid JSON produced by the profiler will cause jq and the automated check to fail.
=> Lint JSON output of profiler with jq on CI

include/topotoolbox.h, src/graphflood/graphflood.c, src/graphflood/priority_flood_standalone.c, src/graphflood/sfgraph.c
This PR patches earlier versions of `graphflood`. These changes need to go ahead before I finish the PR the python frontend (TopoToolbox/pytopotoolbox#57).
After more testing and use, I realised that my custom priority flood (tailored for use with `graphflood`, not for general use - or it can but it require a specific format of boundary condition codes) was sometimes falling bellow floating point precision when trying to impose a minimum slope. I added an argument allowing user to control the magnitude of the imposed slope.
=> Graphflood patch

include/topotoolbox.h, src/fillsinks.c, src/morphology/reconstruct.c, test/random_dem.cpp
The new `bc` argument to `fillsinks` and `fillsinks_hybrid` is a `uint8_t` array of the same dimension as the DEM with a value of 1 at each pixel that should be pinned to its original values in the DEM and 0 otherwise. This allows some additional flexibility in determining the "boundary" of the DEM. For example, if you only wanted to fill a smaller region within a DEM.
It also allows us to flag NaNs, so that we can reproduce the behavior of TopoToolbox v2 with NaNs, resolving #20. Specifically, if pixel `p` of the DEM is a NaN, then setting `dem[p] = -INFINITY` and `bc[p] = 1`, will prevent that pixel from being filled, treating it as a known sink, which is the existing behavior of TopoToolbox v2.
Some changes are also made to src/morphology/reconstruct.c to ensure that the comparisons …
=> Supply boundary conditions to `fillsinks` and `fillsinks_hybrid`

.github/workflows/ci.yaml, .gitmodules, CMakeLists.txt, test/CMakeLists.txt, test/snapshot.cpp
test/snapshot.cpp compares the output of `fillsinks` to the known outputs in the TopoToolbox/snapshot_data repository. It is structured similarly to test/random_dem.cpp, with a class that handles loading all of the data and a `runtests` method that runs the libtopotoolbox functions and the comparisons.
This adds a test-time dependency on GDAL, which is used to read the snapshot data from disk. CMake is used to detect GDAL during compilation. If GDAL is not detected the snapshot tests are not compiled and will not be run by CTest.
The C++17 std::filesystem library is used for cross-platform filesystem access, so the supported C++ standard is incremented in CMakeLists.txt.
The TopoToolbox/snapshot_data repository is added as a submodule at test/snapshots. This repository only contains a …
=> Implement snapshot testing framework

README.md, docs/index.rst
TopoToolbox/topotoolbox is the legacy TopoToolbox v2 repository TopoToolbox/topotoolbox3 is the new one with the libtopotoolbox bindings.
=> Change links to topotoolbox3

src/identifyflats.c, test/snapshot.cpp
Resolves #138
test/snapshot.cpp runs `identifyflats` on the various snapshot data sets.
src/identifyflats.c has one small change to ensure that NaNs are handled consistently with TopoToolbox v2. Neighboring NaNs are treated as if they lie below the current pixel, but NaNs are not themselves flats. fminf ensures consistent NaN treatment, and the NaN equality semantics ensures that NaNs are never set.
The sills are already handled correctly, since they are only compared to neighbors that are known to be flats.
=> Implement snapshot tests for `identifyflats` and handle NaN s

test/snapshot.cpp
This order ensures that we check every pixel that is identified as a flat or a sill in the snapshots. Previously if we never set any pixels in `test_flats`, the tests would still pass.
=> Invert test conditions and assertions in snapshot tests

include/topotoolbox.h, src/CMakeLists.txt, src/cumtrapz.c, src/streamquad.c, test/random_dem.cpp
Resolves #144
include/topotoolbox.h adds interfaces for two variants of cumtrapz for different data types and documents `cumtrapz_f32`.
src/cumtrapz.c adds implementation for the two variants. These are identical to each other except for the data type of the `integral` and `integrand` arguments.
src/CMakeLists.txt adds src/cumtrapz.c to the build system.
test/random_dem.cpp tests cumtrapz by computing the along stream distance using cumtrapz and by explicitly tracing the flow network. First it generates the stream network edge list by thresholding the flow accumulation. Then it runs cumtrapz with a unit integrand. `test_stream_distance` computes the downstream distance for every pixel in the DEM by iterating over the flow network edges computed by `flow_routing_d8_carve` and then compares …
=> Implement cumtrapz

src/gwdt.c
Resolves #146
This change is documented by a comment in gwdt.c, and the tweight definition is left commented out, in case it needs to be replaced in the future.
=> Fix tweight to 1 in `gwdt_computecosts`

.github/workflows/ci.yaml
Continues work on #150
.github.workflows/ci.yaml adds an upload-artifact step to the debug build. This step save the output of the snapshot tests as an artifact and makes it available for download. The original snapshot data as well as output data from any failed test will be saved.
=> Output snapshot artifacts

src/gradient8.c, test/random_dem.cpp
gradient8 as computed by TopoToolbox 2 and described in O'Callaghan and Mark (1984) computes the steepest downward gradient, not the steepest absolute gradient. This commit makes that change in src/gradient8.c and reconfigures the random_dem test in test/random_dem.cpp to test the property that the computed gradient is greater than or equal to the gradients between the central pixel and its nearest neighbors.
@Teschl: while looking at some examples, I noticed that we implemented this incorrectly the first time around. It is an easy fix though. I am pretty sure we don't rely on this behavior in pytopotoolbox or anywhere else, but let me know if you notice anything breaking as a result.
=> Compute gradient8 as the steepest downward gradient

src/Makefile
R package compilation process requires a Makefile, and it cannot use our more complex CMake build system. This Makefile compiles a static library version of libtopotoolbox out of all of the source files in `src/`. It should generally not be used to compile libtopotoolbox because it is not portable to other operating systems.
=> Add a Makefile for use by R

src/gwdt.c
MATLAB's implementation of `gwdt_computecosts` uses a double precision floating point value for `CarveMinVal` even when the costs arrays are `float`. This results in subtle numerical differences between the libtopotoolbox implementation and the MATLAB implementation. This changes libtopotoolbox so that it matches the MATLAB implementation.
This change should be more or less inconsequential from the scientific perspective. I do not believe, for example, that it is responsible for the discrepancies noted in #122, though that hypothesis remains to be confirmed. The change is made only to avoid unnecessary discrepancies between the two implementations so that issues like #122 are easier to resolve.
There is a very slight performance cost to using a `double` rather than a `float` here. …
=> Change CarveMinVal to a double

test/snapshot.cpp
We use GDAL to save the snapshots for diagnostic purposes. GDALDataset::CreateCopy copies all of the metadata from the source data set including the data type. In the case when the output data has a different data type from the source dataset, the data are converted to the type of the source dataset. This works for the existing snapshot tests, but it does not allow us to save auxiliary data unless they have the same type as an available source data set.
This change does not affect the test suite itself.
=> Use GDALDataset::Create rather than GDALDataset::CreateCopy

test/snapshot.cpp
This replaces the custom test output with one that conforms to the Test Anything Protocol version 14. We don't currently use this information because our test runner, ctest, does not do anything, but it provides the same amount of information as we were providing previously in a standardized format.
Related to #158
=> Implement TAP output from snapshot tests

src/drainagebasins.c, test/random_dem.cpp
This PR fixes a problem with drainage basins which would lead to pixels that are not part of the flow network such as NaNs in the DEM being assigned to their own drainage basin.
The problem was that sinks, outlets and invalid pixels are all assigned placeholder edges by `flow_routing_d8_carve` that point from them to -1. We were using this placeholder edge to detect when to create a new drainage basin. This works for the sinks and outlets, but also creates a drainage basin for the invalid pixels. This PR switches this behavior to 1. skip these placeholder edges and 2. test whether the target pixel has not yet been assigned to a drainage basin. This matches the behavior of the MATLAB implementation, leaving invalid pixels with a 0 label for their drainage basin.
This is part of some …
=> Do not assign drainage basins to invalid pixels

include/topotoolbox.h, src/streamquad.c
Resolves #162
These traversals have been added to streamquad.c, which contains the similarly structured streamquad_trapz_{f32,f64}, and which I hope will in the future contain a more complete set of interfaces for integrating over stream networks.
=> Add traversals necessary for trunk

include/topotoolbox.h, src/streamquad.c
This function computes the indegree and outdegree of each node in the stream network by looping over the edge list. This can be used to identify sources, outlets and confluences, which is typically accomplished in TopoToolbox by summing rows and columns of the adjacency matrix.
=> Implement edgelist_degree

include/topotoolbox.h, src/streamquad.c
This could be used to replace the more specific
`flow_accumulation_edgelist` implementation for flow networks, but it can also be used to compute the size of connected components of the stream network.
See the discussion in #164
=> Implement traverse_f32_add_mul

include/topotoolbox.h, src/streamquad.c, test/random_dem.cpp
There are many variants called `propagatevaluesupstream_*` for different input data types. This does duplicate the bodies of these functions, but I am not sure whether the
alternatives (e.g. metaprogramming, pointer casting) are necessarily more maintainable.
A test is added to test/random_dem.cpp to ensure that every propagatevaluesupstream version provides the same answer. This should help make sure that any future changes to
propagatevaluesupstream, such as supporting fill values, are properly duplicated across the different implementations.
=> Implement propagatevaluesupstream

.github/workflows/ci.yaml, test/CMakeLists.txt
Resolves #175 
This replaces the curl script in the CI configuration with a CMake FetchContent declaration. If snapshot data is present in the test/snapshots/data directory during configuration, then it will be used instead of downloading the new snapshot data.
This change increases the duplication of the snapshot version number, which now must be changed in .github/workflows/ci.yaml to make sure that the correct data is cached, and in test/CMakeLists.txt, to make sure the correct data is fetched. The hash of the snapshot archive is also needed by FetchContent, and this is different from the checksums that we provide in the snapshot_data repository.
This change also requires slightly more complicated caching logic in the CI workflow: the location of the cached data is not the location …
=> Download snapshot data using FetchContent

test/CMakeLists.txt
I made this change in #176 because the FindGDAL module is deprecated, but the new find_package support is only provided by GDAL >= 3.5. This works on GitHub Actions, because we run on Ubuntu 24.04, which I believe provides GDAL 3.8. However, my home system is running Ubuntu 22.04, which is still on GDAL 3.4, so I would like to keep the older system around for a while. We should watch out for this deprecation, however.
=> Revert change to GDAL find_package

.github/workflows/ci.yaml, include/topotoolbox.h, src/CMakeLists.txt, src/hillshade.c, test/CMakeLists.txt, test/snapshot.cpp
Resolves #111 
This patch implements `hillshade` for computing hillshade visualizations of digital elevation models. It successfully reproduces the outputs of `hillshade` from TopoToolbox v2 on the snapshot test data.
Two new functions are added to the API. `gradient_secondorder` computes the gradient of the DEM using a second-order finite difference approximation that is equivalent to that used by MATLAB in `surfnorm` and by `numpy.gradient`. This function is used elsewhere by TopoToolbox functions (such as `aspect`) and might be useful in those places, though its performance against optimized versions has not been thoroughly evaluated.
`hillshade` computes the hillshade of the DEM by computing normal vectors using `gradient_secondorder` and evaluating the dot product of the normal …
=> Implement hillshade

src/hillshade.c, test/snapshot.cpp
The azimuth, as described in the documentation, should be in radians clockwise from north, which means we need to subtract 90 degrees (pi/2 radians) to rotate into the standard x-y coordinate system.
=> Correct the hillshade azimuth angle

include/topotoolbox.h, src/hillshade.c, test/snapshot.cpp
This choice of coordinate system is arbitrary, but it makes the most sense to work entirely within a grid-based coordinate system, where the "x" axis increases with the first dimension of the grid and the "y" axis increases with the second dimension of the grid. This uses no external information on the orientation of the image. However, the relationship between grid coordinates and geographic coordinates depends on both the coordinate system of the image and the memory layout of the grid.
GDAL's default coordinate system has the first dimension increasing from the left to the right as one looks at the image, while the second dimension increases from top to bottom. If this image is oriented so that north is up, this means that the azimuth desired by `hillshade` increases from the east (0 …
=> Clearly specify the grid-centered coordinate system in hillshade

.github/workflows/release.yaml
This checks that the release job is running in the TopoToolbox repository rather than a fork and will only make the weekly release if it is running in the main repository.
=> Only run the release workflow on the main repository

include/topotoolbox.h, src/streamquad.c
For consistency with previous traversals, this should be `or_and` not `and_or`.
=> Rename the downstream Boolean semiring traversal

include/topotoolbox.h, src/flow_routing.c, test/random_dem.cpp
Flow routing should produce the same results for identical DEMs stored in either row- or column-major order. However, we search sequentially through neighboring pixels to find the steepest gradient, and we choose the first neighbor we encounter if two neighbors have the same gradient. For column-major arrays, we start with the east neighbor and check in a clockwise direction. But for row-major arrays, using the same offsets in the i and j directions starts with the south neighbor and checks counterclockwise.
This change introduces a new parameter (`order`) that is zero for column-major arrays and one for row-major arrays. Think about it as the index of the dimension whose index changes the fastest as you iterate linearly through the array. This parameter is used to construct the offset …
=> Modify offsets to make row- and column-major indexing consistent 

include/topotoolbox.h, src/streamquad.c, test/random_dem.cpp
As described in https://github.com/TopoToolbox/libtopotoolbox/issues/164, 
this makes the semiring pattern in the traversal more obvious and parallels
the naming of `traverse_down_u32_or_and`.
A test is added to test/random_dem.cpp that computes drainage basins
using traverse_up_u32_or_and and ensures that it is identical to our
existing drainagebasins computation. This also tries a new testing
pattern where test-specific data is initialized within the test
function rather than as part of the very large FlowRoutingData class.
=> Add bitwise or accumulation to traverse_up_u32_or_and

include/topotoolbox.h
Many of these were copy-and-pasted from each other, which resulted in inconsistencies between the documentation and the actual function. This change also makes the documentation more consistent across the various functions.
=> Clarify network traversal documentation

.github/workflows/ci.yaml, src/Makefile
This change introduced in #178 was not propagated to the Makefile, which is used in the topotoolboxr build.
=> Rename morphology/reconstruct.c to reconstruct.c in the Makefile

src/knickpoints.c
Following the MATLAB implementation, we recursively updated the elevation from upstream to downstream according to the minimum gradient found so far. This accumulates floating point error rather severely. This change computes the elevation at each point along the stream from the initial point, which should avoid that error accumulation.
=> More precisely correct elevations in lowerenv

.github/workflows/ci.yaml, src/Makefile
Resolves #200
This macro turns off the asserts that we use for testing in various functions. CMake does this for us on many platforms, but R uses our Makefile to compile libtopotoolbox, and for some reason NDEBUG does not get properly defined on macos, causing the asserts to be left in the compiled code, and R does not accept C code that has asserts, because it could potentially abort the R session.
I have also added a test to the CI configuration that build the Makefiles in CI on ubuntu and macos and check that no asserts are left in the symbol table.
=> Define the NDEBUG macro in the Makefile
